import os
import logging
from typing import Optional
import groq
from groq import (
    Groq,
    APIConnectionError,
    APITimeoutError,
    AuthenticationError,
    RateLimitError,
    APIStatusError,
    GroqError,
)
from config import settings

logger = logging.getLogger("labexplain.llm")

# Active Groq production models
PRIMARY_MODELS = [
    "llama-3.3-70b-versatile",
    "llama3-8b-8192",
    "mixtral-8x7b-32768",
    "gemma2-9b-it",
    "qwen/qwen3.8-27b",
    "openai/gpt-oss-120b",
]

MODEL_NAME = os.environ.get("GROQ_MODEL", PRIMARY_MODELS[0])

# Lazy-loaded Groq client
_client: Optional[Groq] = None


def get_groq_client() -> Groq:
    """
    Returns an initialized Groq client instance.
    Raises ValueError if GROQ_API_KEY is missing.
    """
    global _client
    api_key = settings.GROQ_API_KEY
    if not api_key:
        settings.reload()
        api_key = settings.GROQ_API_KEY

    if not api_key:
        raise ValueError(
            "GROQ_API_KEY is not configured on this lab server. "
            "Please add your key to the .env file or set GROQ_API_KEY in your environment."
        )
    if _client is None or getattr(_client, "api_key", None) != api_key:
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are an encouraging, patient, and knowledgeable university computer science lab tutor.
Your mission is to guide undergraduate students through unfamiliar syntax and cryptic runtime concepts in their lab code without intimidating jargon.
Break down their code clearly, empathetically, and with high pedagogical rigor.

Always structure your explanation using clean Markdown with this exact format:

### 📝 Overview
A clear 1–2 sentence high-level summary of what this code snippet accomplishes.

### 🔍 Line-by-Line Breakdown
For each line or logical statement in the code snippet, provide:
- **Line**: `[exact line or logical statement]`
- **What it does**: A clear 1–2 sentence plain-English explanation.
- **Why it matters / Gotchas**: Subtle concepts (e.g., context managers closing files automatically, off-by-one errors, pointer referencing/dereferencing, recursion base cases, scope, mutability, edge cases).

### 💡 Tutor's Lab Takeaway
A brief, supportive takeaway or rule-of-thumb that the student can apply during their university lab exam or assignment.
"""


def explain_snippet(code: str, language: str = "python") -> str:
    """
    Sends the student's code snippet to Groq running llama-3.1-8b-instant for line-by-line explanation.

    Args:
        code: The source code snippet pasted by the student.
        language: The programming language (e.g., python, c, cpp, java, rust, javascript).

    Returns:
        Structured markdown explanation generated by the open-weight LLM.

    Raises:
        RuntimeError: If Groq inference fails due to connection, auth, or rate limit issues.
        ValueError: If configuration or input parameters are invalid.
    """
    clean_code = code.strip()
    if not clean_code:
        raise ValueError("Cannot explain an empty code snippet.")

    user_prompt = f"""Please analyze this {language} code snippet line-by-line for an undergraduate student in a university lab:

```{language}
{clean_code}
```

Follow the structured output format strictly (Overview, Line-by-Line Breakdown with Line, What it does, and Why it matters / Gotchas, followed by Tutor's Lab Takeaway).
"""

    try:
        client = get_groq_client()
        primary_model = getattr(settings, "MODEL_NAME", None) or MODEL_NAME

        # Prioritize primary configured model; fallback through PRIMARY_MODELS if 404/400 occurs
        models_to_try = [primary_model]
        for m in PRIMARY_MODELS:
            if m not in models_to_try:
                models_to_try.append(m)

        last_api_error = None

        for current_model in models_to_try:
            try:
                response = client.chat.completions.create(
                    model=current_model,
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=0.2,
                    max_tokens=2048,
                )

                choice = response.choices[0]
                explanation = choice.message.content
                if not explanation:
                    raise RuntimeError("The model returned an empty response. Please try again.")

                # Cache working model to avoid repeated fallback retries on subsequent requests
                if current_model != models_to_try[0]:
                    logger.info(f"Promoting working model '{current_model}' as active model.")
                    settings.MODEL_NAME = current_model

                return explanation.strip()

            except APIStatusError as exc:
                err_msg = str(getattr(exc, "message", exc)).lower()
                # If model returned 404 (not found), decommissioned, or 400 bad request, try next model in PRIMARY_MODELS
                is_model_err = (
                    exc.status_code in (404, 400)
                    or "not_found" in err_msg
                    or "does not exist" in err_msg
                    or "decommissioned" in err_msg
                )
                if is_model_err and current_model != models_to_try[-1]:
                    logger.warning(
                        f"Model '{current_model}' unavailable ({exc.status_code}): {exc.message}. "
                        "Attempting fallback to next active production model..."
                    )
                    last_api_error = exc
                    continue
                raise

        if last_api_error:
            raise last_api_error

    except AuthenticationError as exc:
        logger.error(f"Groq authentication error: {exc}")
        raise RuntimeError(
            "Authentication failed with the Groq API. Please verify that GROQ_API_KEY is valid."
        ) from exc

    except RateLimitError as exc:
        logger.warning(f"Groq rate limit exceeded: {exc}")
        raise RuntimeError(
            "The lab AI service is temporarily rate-limited. Please wait 15–30 seconds and try again."
        ) from exc

    except (APITimeoutError, APIConnectionError) as exc:
        logger.error(f"Groq network/timeout error: {exc}")
        raise RuntimeError(
            "Network timeout connecting to the AI inference service. Please check your internet connection."
        ) from exc

    except APIStatusError as exc:
        logger.error(f"Groq API status error ({exc.status_code}): {exc.message}")
        raise RuntimeError(
            f"Groq inference service returned error code {exc.status_code}: {exc.message}"
        ) from exc

    except GroqError as exc:
        logger.error(f"Groq general error: {exc}")
        raise RuntimeError(f"An error occurred with the AI tutor service: {str(exc)}") from exc

    except ValueError:
        raise

    except Exception as exc:
        logger.exception(f"Unexpected error during code explanation: {exc}")
        raise RuntimeError(f"Unexpected error while analyzing code: {str(exc)}") from exc
