import logging
from typing import Optional
import groq
from groq import (
    Groq,
    APIConnectionError,
    APITimeoutError,
    AuthenticationError,
    RateLimitError,
    APIStatusError,
    GroqError,
)
from config import settings

logger = logging.getLogger("labexplain.llm")

# Lazy-loaded Groq client
_client: Optional[Groq] = None


def get_groq_client() -> Groq:
    """
    Returns an initialized Groq client instance.
    Raises ValueError if GROQ_API_KEY is missing.
    """
    global _client
    api_key = settings.GROQ_API_KEY
    if not api_key:
        raise ValueError(
            "GROQ_API_KEY is not configured on this lab server. "
            "Please check the .env file or set GROQ_API_KEY in your environment."
        )
    if _client is None:
        _client = Groq(api_key=api_key)
    return _client


SYSTEM_PROMPT = """You are an encouraging, patient, and knowledgeable university computer science lab tutor.
Your mission is to guide undergraduate students through unfamiliar syntax and cryptic runtime concepts in their lab code without intimidating jargon.
Break down their code clearly, empathetically, and with high pedagogical rigor.

Always structure your explanation using clean Markdown with this exact format:

### 📝 Overview
A clear 1–2 sentence high-level summary of what this code snippet accomplishes.

### 🔍 Line-by-Line Breakdown
For each line or logical statement in the code snippet, provide:
- **Line**: `[exact line or logical statement]`
- **What it does**: A clear 1–2 sentence plain-English explanation.
- **Why it matters / Gotchas**: Subtle concepts (e.g., context managers closing files automatically, off-by-one errors, pointer referencing/dereferencing, recursion base cases, scope, mutability, edge cases).

### 💡 Tutor's Lab Takeaway
A brief, supportive takeaway or rule-of-thumb that the student can apply during their university lab exam or assignment.
"""


def explain_snippet(code: str, language: str = "python") -> str:
    """
    Sends the student's code snippet to Groq running gemma2-9b-it for line-by-line explanation.

    Args:
        code: The source code snippet pasted by the student.
        language: The programming language (e.g., python, c, cpp, java, rust, javascript).

    Returns:
        Structured markdown explanation generated by Gemma 2.

    Raises:
        RuntimeError: If Groq inference fails due to connection, auth, or rate limit issues.
        ValueError: If configuration or input parameters are invalid.
    """
    clean_code = code.strip()
    if not clean_code:
        raise ValueError("Cannot explain an empty code snippet.")

    user_prompt = f"""Please analyze this {language} code snippet line-by-line for an undergraduate student in a university lab:

```{language}
{clean_code}
```

Follow the structured output format strictly (Overview, Line-by-Line Breakdown with Line, What it does, and Why it matters / Gotchas, followed by Tutor's Lab Takeaway).
"""

    try:
        client = get_groq_client()
        response = client.chat.completions.create(
            model=settings.MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.2,
            max_tokens=2048,
        )

        choice = response.choices[0]
        explanation = choice.message.content
        if not explanation:
            raise RuntimeError("The model returned an empty response. Please try again.")

        return explanation.strip()

    except AuthenticationError as exc:
        logger.error(f"Groq authentication error: {exc}")
        raise RuntimeError(
            "Authentication failed with the Groq API. Please verify that GROQ_API_KEY is valid."
        ) from exc

    except RateLimitError as exc:
        logger.warning(f"Groq rate limit exceeded: {exc}")
        raise RuntimeError(
            "The lab AI service is temporarily rate-limited. Please wait 15–30 seconds and try again."
        ) from exc

    except (APITimeoutError, APIConnectionError) as exc:
        logger.error(f"Groq network/timeout error: {exc}")
        raise RuntimeError(
            "Network timeout connecting to the Gemma 2 inference service. Please check your internet connection."
        ) from exc

    except APIStatusError as exc:
        logger.error(f"Groq API status error ({exc.status_code}): {exc.message}")
        raise RuntimeError(
            f"Groq inference service returned error code {exc.status_code}: {exc.message}"
        ) from exc

    except GroqError as exc:
        logger.error(f"Groq general error: {exc}")
        raise RuntimeError(f"An error occurred with the AI tutor service: {str(exc)}") from exc

    except ValueError:
        raise

    except Exception as exc:
        logger.exception(f"Unexpected error during code explanation: {exc}")
        raise RuntimeError(f"Unexpected error while analyzing code: {str(exc)}") from exc
