from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field, field_validator
from config import settings
from services.llm_service import explain_snippet

router = APIRouter(prefix="/api", tags=["explain"])


class ExplainRequest(BaseModel):
    pin: str = Field(
        ...,
        min_length=1,
        max_length=32,
        description="6-digit lab session PIN for zero-login authentication",
        examples=["482910"],
    )
    code: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="Code snippet to explain (max 4000 characters)",
        examples=["with open('data.txt', 'r') as f:\n    content = f.read()"],
    )
    language: str = Field(
        default="python",
        description="Programming language of the snippet",
        examples=["python"],
    )

    @field_validator("code")
    @classmethod
    def validate_code_not_blank(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Code snippet cannot be empty or solely whitespace.")
        if len(v) > 4000:
            raise ValueError("Code snippet exceeds maximum allowed length of 4000 characters.")
        return v

    @field_validator("language")
    @classmethod
    def sanitize_language(cls, v: str) -> str:
        cleaned = v.strip().lower()
        return cleaned if cleaned else "python"


class ExplainResponse(BaseModel):
    explanation: str = Field(
        ...,
        description="Pedagogical, line-by-line explanation generated by Gemma 2",
    )


@router.post(
    "/explain",
    response_model=ExplainResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate a line-by-line pedagogical code explanation",
    description=(
        "Authenticates using the shared university lab session PIN, "
        "validates the submitted code snippet, and generates a structured "
        "pedagogical explanation powered by Google Gemma 2 (gemma2-9b-it)."
    ),
)
async def explain_code(payload: ExplainRequest) -> ExplainResponse:
    # 1. Validate session PIN (Zero-login lab authentication)
    if not settings.verify_session_pin(payload.pin):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid session PIN. Please check the 6-digit lab PIN provided by your instructor or TA.",
        )

    # 2. Invoke Gemma 2 inference service
    try:
        explanation_markdown = explain_snippet(
            code=payload.code,
            language=payload.language,
        )
        return ExplainResponse(explanation=explanation_markdown)

    except ValueError as ve:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(ve),
        )
    except RuntimeError as re:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(re),
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An unexpected internal error occurred: {str(exc)}",
        )
